In [1]:
import numpy as np
array = np.array([1,3,4,2,9,6])

In [2]:
print(array > 4)

[False False False False  True  True]


In [3]:
2 < 6

True

In [4]:
a = np.array([7,5,3,1,9,0,2,4,6])
b = np.array([6,4,2,0,9,1,3,5,7])
print(a > b)

[ True  True  True  True False False False False False]


In [5]:
True == 1

True

In [6]:
True and False

False

In [7]:
x = 2; y = 6
x > 1 and y < 4

False

In [8]:
x > 1 or y < 4

True

In [9]:
not(x > 3)

True

In [11]:
np.logical_and(a > 2, b < 4)

array([False, False,  True, False, False, False, False, False, False], dtype=bool)

In [12]:
np.logical_or(a > 2, b < 4)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [14]:
np.logical_and(a > 2, a < 6)

array([False,  True,  True, False, False, False, False,  True, False], dtype=bool)

In [18]:
y = 7
if y > 7:
    print(str(y) + " es menor que 7")
elif y > 6:
    print(str(y) + " es menor que 6")
else:
    print(" y es " + str(y))

7 es menor que 6


In [20]:
import pandas as pd
data = pd.read_csv('data_fanpage.csv')
print(data)

      id  social_network_account_id  social_network_account_followers  \
0     16                      38614                           1965664   
1     19                      28990                            176909   
2     20                      29189                           2032491   
3      1                      35837                           1468492   
4      5                      30603                            451471   
5     37                      28613                            111700   
6      7                      35875                           1466535   
7     36                      30275                            229998   
8     24                      25783                             25658   
9     15                      29387                            900687   
10    21                      29406                              2177   
11    22                      26843                             16749   
12     8                      28631                

In [22]:
data["code_iso"] #data.loc[:,[code_iso]]

0      PE
1      PE
2      PE
3      MX
4      GT
5      CO
6      CO
7      MX
8      CO
9      PE
10     CO
11     CO
12     CO
13     PE
14     CO
15     CO
16     CO
17     CO
18     MX
19     CO
20     CO
21     PE
22     CO
23     PE
24     PE
25     PE
26     PE
27     PE
28     PE
29     PE
       ..
694    PE
695    CO
696    CO
697    MX
698    CO
699    MX
700    PE
701    CO
702    MX
703    CO
704    PE
705    CO
706    MX
707    CO
708    CO
709    MX
710    MX
711    CO
712    MX
713    MX
714    CO
715    MX
716    PE
717    CO
718    CO
719    PE
720    PE
721    US
722    MX
723    PE
Name: code_iso, dtype: object

In [24]:
pe=data["code_iso"]=="PE"
print(pe)

0       True
1       True
2       True
3      False
4      False
5      False
6      False
7      False
8      False
9       True
10     False
11     False
12     False
13      True
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21      True
22     False
23      True
24      True
25      True
26      True
27      True
28      True
29      True
       ...  
694     True
695    False
696    False
697    False
698    False
699    False
700     True
701    False
702    False
703    False
704     True
705    False
706    False
707    False
708    False
709    False
710    False
711    False
712    False
713    False
714    False
715    False
716     True
717    False
718    False
719     True
720     True
721    False
722    False
723     True
Name: code_iso, dtype: bool


In [25]:
data[pe]

id  social_network_account_id  social_network_account_followers  \
0     16                      38614                           1965664   
1     19                      28990                            176909   
2     20                      29189                           2032491   
9     15                      29387                            900687   
13    18                      31083                           1466515   
21    14                      29546                             14665   
23    38                      29492                            135018   
24    39                      36330                             14728   
25    40                      28248                             30675   
26    41                      28464                            107963   
27    42                      28208                             18245   
28    43                      29221                             59057   
29    44                      34460                              9571   
42    89                      29109                            401413   
61    90                      34950                            121893   
67    81                      28248                             30675   
68    82                      30719                            456786   
69    83                      28985                            239389   
70    84                      39414                            242665   
71    85                      29221                             59057   
72    86                      39613                            137593   
73    87                      30709                             65895   
84    92                      28285                           1009218   
87   119                      30769                            486520   
89   123                      37858                                 6   
90   124                      37858                                 6   
91   125                      37858                                 6   
100  114                      37851                             26658   
101  112                      34329                            154937   
102  117                      40026                           3235921   
..   ...                        ...                               ...   
566  322                      41652                            229388   
569  359                      29257                            595742   
571  216                      40026                           3235921   
572  358                      38505                           1049579   
573  351                      34329                            154937   
582  512                      29257                            595742   
584  498                      29221                             59057   
593  564                      39726                            458592   
600  559                      29257                            595742   
605  625                      31044                            717960   
609  652                      40404                             95819   
615  508                      29314                            293030   
617  646                      38614                           1965664   
620  651                      28985                            239389   
632  563                      47126                            226747   
634  632                      40404                             95819   
636  647                      40404                             95819   
638  543                      29257                            595742   
653  586                      44500                            140406   
657  465                      29387                            900687   
679  707                      50518                            336051   
684  723                      29257                            595742   
692  658                      34950                            1

In [28]:
data[data["code_iso"] == "PE"]

id  social_network_account_id  social_network_account_followers  \
0     16                      38614                           1965664   
1     19                      28990                            176909   
2     20                      29189                           2032491   
9     15                      29387                            900687   
13    18                      31083                           1466515   
21    14                      29546                             14665   
23    38                      29492                            135018   
24    39                      36330                             14728   
25    40                      28248                             30675   
26    41                      28464                            107963   
27    42                      28208                             18245   
28    43                      29221                             59057   
29    44                      34460                              9571   
42    89                      29109                            401413   
61    90                      34950                            121893   
67    81                      28248                             30675   
68    82                      30719                            456786   
69    83                      28985                            239389   
70    84                      39414                            242665   
71    85                      29221                             59057   
72    86                      39613                            137593   
73    87                      30709                             65895   
84    92                      28285                           1009218   
87   119                      30769                            486520   
89   123                      37858                                 6   
90   124                      37858                                 6   
91   125                      37858                                 6   
100  114                      37851                             26658   
101  112                      34329                            154937   
102  117                      40026                           3235921   
..   ...                        ...                               ...   
566  322                      41652                            229388   
569  359                      29257                            595742   
571  216                      40026                           3235921   
572  358                      38505                           1049579   
573  351                      34329                            154937   
582  512                      29257                            595742   
584  498                      29221                             59057   
593  564                      39726                            458592   
600  559                      29257                            595742   
605  625                      31044                            717960   
609  652                      40404                             95819   
615  508                      29314                            293030   
617  646                      38614                           1965664   
620  651                      28985                            239389   
632  563                      47126                            226747   
634  632                      40404                             95819   
636  647                      40404                             95819   
638  543                      29257                            595742   
653  586                      44500                            140406   
657  465                      29387                            900687   
679  707                      50518                            336051   
684  723                      29257                            595742   
692  658                      34950                            1

In [35]:
pe_f = data[np.logical_and(data["social_network_account_followers"] > 0, data["code_iso"] == "PE")]
pe_f.shape

(156, 17)